In [260]:
import pandas as pd

In [261]:
df = pd.read_excel("dummy_qc_data.xlsx")

In [262]:
df.head()

,Batch_Name,Date,Week,User,Error_Type,QC_Result,OA_Charge_ID,Comments,QC_User,Scenario
0,Crawley_11,2026-03-16,1,Ethan Williams,No Error,Correct,OA000835,Minor advisory noted,Renuka,Link Cleanse
1,Crawley_11,2026-03-16,1,Sophie Evans,No Error,Correct,OA000839,NaN,Kritika,Link
2,Crawley_11,2026-03-16,1,Maya Patel,No Error,Correct,OA000845,NaN,Kritika,Draw
3,Crawley_11,2026-03-16,1,Daniel Jones,No Error,Correct,OA000859,Minor advisory noted,Kritika,Plan
4,Crawley_11,2026-03-16,1,Ethan Williams,No Error,Correct,OA000860,NaN,Renuka,Link

In [263]:
df.shape

(1000, 10)

In [264]:
df.columns

Index(['Batch_Name', 'Date', 'Week', 'User', 'Error_Type', 'QC_Result',
       'OA_Charge_ID', 'Comments', 'QC_User', 'Scenario'],
      dtype='object')

In [265]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Batch_Name    1000 non-null   object
 1   Date          1000 non-null   datetime64[ns]
 2   Week          1000 non-null   int64
 3   User          1000 non-null   object
 4   Error_Type    1000 non-null   object
 5   QC_Result     1000 non-null   object
 6   OA_Charge_ID  1000 non-null   object
 7   Comments      455 non-null    object
 8   QC_User       1000 non-null   object
 9   Scenario      1000 non-null   object
dtypes: datetime64[ns](1), int64(1), object(8)
memory usage: 78.3+ KB

In [266]:
df.isnull().sum()

Batch_Name        0
Date              0
Week              0
User              0
Error_Type        0
QC_Result         0
OA_Charge_ID      0
Comments        545
QC_User           0
Scenario          0
dtype: int64

In [267]:
df["QC_Result"].unique()

array(['Correct', 'Error'], dtype=object)

In [268]:
df["Error_Type"].unique()

array(['No Error', 'Over Capture', 'Under Capture', 'Query', 'Wrong Tag',
       'Wrong Location'], dtype=object)

In [269]:
df[(df["QC_Result"] == "Correct") & (df["Error_Type"] != "No Error")]

Empty DataFrame
Columns: [Batch_Name, Date, Week, User, Error_Type, QC_Result, OA_Charge_ID, Comments, QC_User, Scenario]
Index: []

In [270]:
df[(df["QC_Result"] == "Error") & (df["Error_Type"] == "No Error")]

Empty DataFrame
Columns: [Batch_Name, Date, Week, User, Error_Type, QC_Result, OA_Charge_ID, Comments, QC_User, Scenario]
Index: []

In [271]:
df["Scenario"].unique()

array(['Link Cleanse', 'Link', 'Draw', 'Plan'], dtype=object)

In [272]:
df["User"].unique()

array(['Ethan Williams', 'Sophie Evans', 'Maya Patel', 'Daniel Jones',
       'Sam Taylor', 'Noah Davies', 'Jamie Smith', 'Priya Shah ',
       'Alex Morgan', 'Olivia Brown', 'Jamie Smith ', 'Priya Shah',
       ' Alex Morgan', 'Alex  Morgan', ' JAMIE SMITH', 'Priya  Shah'],
      dtype=object)

In [273]:
df["User"].nunique()

16

In [274]:
df["User"].value_counts()

User
Ethan Williams    108
Sam Taylor        107
Sophie Evans      104
Maya Patel        101
Noah Davies       101
Jamie Smith       101
Daniel Jones       96
Priya Shah         93
Olivia Brown       92
Alex Morgan        80
Jamie Smith         4
Alex  Morgan        4
Priya Shah          3
Priya  Shah         3
 Alex Morgan        2
 JAMIE SMITH        1
Name: count, dtype: int64

In [275]:
df["User_Clean"] = df["User"].str.strip()

In [276]:
df["User_Clean"].nunique()

13

In [277]:
df["User_Clean"] = df["User_Clean"].str.title()

In [278]:
df["User_Clean"].nunique()

12

In [279]:
df["User_Clean"].unique()

array(['Ethan Williams', 'Sophie Evans', 'Maya Patel', 'Daniel Jones',
       'Sam Taylor', 'Noah Davies', 'Jamie Smith', 'Priya Shah',
       'Alex Morgan', 'Olivia Brown', 'Alex  Morgan', 'Priya  Shah'],
      dtype=object)

In [280]:
df["User_Clean"] = df["User_Clean"].apply(
    lambda x: " ".join(x.split())
)

In [281]:
df["User_Clean"].nunique()

10

In [282]:
df["User_Clean"].value_counts()

User_Clean
Ethan Williams    108
Sam Taylor        107
Jamie Smith       106
Sophie Evans      104
Maya Patel        101
Noah Davies       101
Priya Shah         99
Daniel Jones       96
Olivia Brown       92
Alex Morgan        86
Name: count, dtype: int64

In [283]:
df['OA_Charge_ID'].nunique()

1000

In [284]:
df.shape[0]

1000

In [285]:
df['Date'].min()

Timestamp('2026-01-05 00:00:00')

In [286]:
df['Date'].max()

Timestamp('2026-03-27 00:00:00')

In [287]:
df['Week'].unique()

array([1, 2], dtype=int64)

In [288]:
# to check for each batch, which weeks does it contain
df.groupby("Batch_Name")["Week"].unique()

Batch_Name
Crawley_11           [1, 2]
Dartford_176         [1, 2]
Exeter_145           [1, 2]
Monmouthshire_145    [1, 2]
Powys_90             [1, 2]
Test Valley_154      [1, 2]
Name: Week, dtype: object

In [289]:
df["Batch_Name"].value_counts()

Batch_Name
Dartford_176         167
Monmouthshire_145    167
Powys_90             167
Test Valley_154      167
Crawley_11           166
Exeter_145           166
Name: count, dtype: int64

In [290]:
df["QC_User"].value_counts()

QC_User
Renuka     515
Kritika    485
Name: count, dtype: int64

In [291]:
df["QC_Result"].value_counts()

QC_Result
Correct    944
Error       56
Name: count, dtype: int64

In [292]:
df.groupby("Batch_Name")["OA_Charge_ID"].count()

Batch_Name
Crawley_11           166
Dartford_176         167
Exeter_145           166
Monmouthshire_145    167
Powys_90             167
Test Valley_154      167
Name: OA_Charge_ID, dtype: int64

In [293]:
# Automated QC metrics

In [294]:
# total QC Records
df.groupby("Batch_Name")["OA_Charge_ID"].count()

Batch_Name
Crawley_11           166
Dartford_176         167
Exeter_145           166
Monmouthshire_145    167
Powys_90             167
Test Valley_154      167
Name: OA_Charge_ID, dtype: int64

In [295]:
# Errors per batch
# for each batch how many QC records were found to contain errors?
df[df["QC_Result"] == "Error"].groupby("Batch_Name")["OA_Charge_ID"].count()

Batch_Name
Crawley_11            6
Dartford_176         11
Exeter_145           11
Monmouthshire_145     5
Powys_90             13
Test Valley_154      10
Name: OA_Charge_ID, dtype: int64

In [296]:
# Correct records per batch
df[df["QC_Result"] == "Correct"].groupby("Batch_Name")["OA_Charge_ID"].count()

Batch_Name
Crawley_11           160
Dartford_176         156
Exeter_145           155
Monmouthshire_145    162
Powys_90             154
Test Valley_154      157
Name: OA_Charge_ID, dtype: int64

In [297]:
total_qc = df.groupby("Batch_Name")["OA_Charge_ID"].count()

In [298]:
errors = df[df["QC_Result"] == "Error"].groupby("Batch_Name")["OA_Charge_ID"].count()

In [299]:
correct = df[df["QC_Result"] == "Correct"].groupby("Batch_Name")["OA_Charge_ID"].count()

In [300]:
metrics = pd.DataFrame({
    "Total_QC": total_qc,
    "Correct": correct,
    "Errors": errors
})

In [301]:
metrics

                   Total_QC  Correct  Errors
Batch_Name
Crawley_11              166      160       6
Dartford_176            167      156      11
Exeter_145              166      155      11
Monmouthshire_145       167      162       5
Powys_90                167      154      13
Test Valley_154         167      157      10

In [302]:
total_qc.index

Index(['Crawley_11', 'Dartford_176', 'Exeter_145', 'Monmouthshire_145',
       'Powys_90', 'Test Valley_154'],
      dtype='object', name='Batch_Name')

In [303]:
total_qc.name

'OA_Charge_ID'

In [304]:
# calculate the error rate
metrics["Error_Rate"] = metrics["Errors"]/metrics["Total_QC"] * 100

In [305]:
metrics

                   Total_QC  Correct  Errors  Error_Rate
Batch_Name
Crawley_11              166      160       6    3.614458
Dartford_176            167      156      11    6.586826
Exeter_145              166      155      11    6.626506
Monmouthshire_145       167      162       5    2.994012
Powys_90                167      154      13    7.784431
Test Valley_154         167      157      10    5.988024

In [306]:
# calculate the quality rate
metrics["Quality_Rate"] = metrics["Correct"]/metrics["Total_QC"] * 100

In [307]:
metrics

                   Total_QC  Correct  Errors  Error_Rate  Quality_Rate
Batch_Name
Crawley_11              166      160       6    3.614458     96.385542
Dartford_176            167      156      11    6.586826     93.413174
Exeter_145              166      155      11    6.626506     93.373494
Monmouthshire_145       167      162       5    2.994012     97.005988
Powys_90                167      154      13    7.784431     92.215569
Test Valley_154         167      157      10    5.988024     94.011976

In [308]:
# Error type analysis
# What types of errors are driving the QC performance of each batch

df.groupby("Batch_Name")["Error_Type"].value_counts()

Batch_Name         Error_Type
Crawley_11         No Error          160
                   Over Capture        2
                   Under Capture       2
                   Query               1
                   Wrong Tag           1
Dartford_176       No Error          156
                   Query               6
                   Over Capture        2
                   Under Capture       1
                   Wrong Location      1
                   Wrong Tag           1
Exeter_145         No Error          155
                   Wrong Tag           4
                   Over Capture        2
                   Query               2
                   Under Capture       2
                   Wrong Location      1
Monmouthshire_145  No Error          162
                   Wrong Tag           3
                   Under Capture       1
                   Wrong Location      1
Powys_90           No Error          154
                   Query               4
                   Wrong Tag           3
                   Over Capture        2
                   Under Capture       2
                   Wrong Location      2
Test Valley_154    No Error          157
                   Wrong Tag           4
                   Under Capture       3
                   Query               2
                   Over Capture        1
Name: count, dtype: int64

In [309]:
# creating a filtered data frame containing only records where error type is not no error

error_df = df[df["Error_Type"] != "No Error"]

In [310]:
error_df.shape

(56, 11)

In [311]:
error_df.groupby("Batch_Name")["Error_Type"].value_counts()

Batch_Name         Error_Type
Crawley_11         Over Capture      2
                   Under Capture     2
                   Query             1
                   Wrong Tag         1
Dartford_176       Query             6
                   Over Capture      2
                   Under Capture     1
                   Wrong Location    1
                   Wrong Tag         1
Exeter_145         Wrong Tag         4
                   Over Capture      2
                   Query             2
                   Under Capture     2
                   Wrong Location    1
Monmouthshire_145  Wrong Tag         3
                   Under Capture     1
                   Wrong Location    1
Powys_90           Query             4
                   Wrong Tag         3
                   Over Capture      2
                   Under Capture     2
                   Wrong Location    2
Test Valley_154    Wrong Tag         4
                   Under Capture     3
                   Query             2
                   Over Capture      1
Name: count, dtype: int64

In [312]:
error_df["Error_Type"].value_counts()

Error_Type
Wrong Tag         16
Query             15
Under Capture     11
Over Capture       9
Wrong Location     5
Name: count, dtype: int64

In [313]:
# how many wrong tag errors does each batch have?
wrong_tag = df[df["Error_Type"] == "Wrong Tag"].groupby("Batch_Name")["OA_Charge_ID"].count()

In [314]:
metrics["Wrong_Tag"] = wrong_tag

In [315]:
metrics

,Total_QC,Correct,Errors,Error_Rate,Quality_Rate,Wrong_Tag
Batch_Name,,,,,,
Crawley_11,166,160,6,3.614458,96.385542,1
Dartford_176,167,156,11,6.586826,93.413174,1
Exeter_145,166,155,11,6.626506,93.373494,4
Monmouthshire_145,167,162,5,2.994012,97.005988,3
Powys_90,167,154,13,7.784431,92.215569,3
Test Valley_154,167,157,10,5.988024,94.011976,4

In [316]:
metrics["Wrong_Tag_%"] = metrics["Wrong_Tag"] / metrics["Errors"] * 100

In [317]:
# for converting it from series to data frame
error_analysis = error_df.groupby("Batch_Name")["Error_Type"].value_counts().to_frame()

In [318]:
error_analysis

                                  count
Batch_Name        Error_Type
Crawley_11        Over Capture        2
                  Under Capture       2
                  Query               1
                  Wrong Tag           1
Dartford_176      Query               6
                  Over Capture        2
                  Under Capture       1
                  Wrong Location      1
                  Wrong Tag           1
Exeter_145        Wrong Tag           4
                  Over Capture        2
                  Query               2
                  Under Capture       2
                  Wrong Location      1
Monmouthshire_145 Wrong Tag           3
                  Under Capture       1
                  Wrong Location      1
Powys_90          Query               4
                  Wrong Tag           3
                  Over Capture        2
                  Under Capture       2
                  Wrong Location      2
Test Valley_154   Wrong Tag           4
                  Under Capture       3
                  Query               2
                  Over Capture        1

In [319]:
# making the structure more table like using reset index 
error_analysis = error_df.groupby("Batch_Name")["Error_Type"].value_counts().to_frame().reset_index()

In [320]:
error_analysis

           Batch_Name      Error_Type  count
0          Crawley_11    Over Capture      2
1          Crawley_11   Under Capture      2
2          Crawley_11           Query      1
3          Crawley_11       Wrong Tag      1
4        Dartford_176           Query      6
5        Dartford_176    Over Capture      2
6        Dartford_176   Under Capture      1
7        Dartford_176  Wrong Location      1
8        Dartford_176       Wrong Tag      1
9          Exeter_145       Wrong Tag      4
10         Exeter_145    Over Capture      2
11         Exeter_145           Query      2
12         Exeter_145   Under Capture      2
13         Exeter_145  Wrong Location      1
14  Monmouthshire_145       Wrong Tag      3
15  Monmouthshire_145   Under Capture      1
16  Monmouthshire_145  Wrong Location      1
17           Powys_90           Query      4
18           Powys_90       Wrong Tag      3
19           Powys_90    Over Capture      2
20           Powys_90   Under Capture      2
21           Powys_90  Wrong Location      2
22    Test Valley_154       Wrong Tag      4
23    Test Valley_154   Under Capture      3
24    Test Valley_154           Query      2
25    Test Valley_154    Over Capture      1

In [321]:
# renaming the column count to error count
error_analysis = error_analysis.rename(columns={"count": "Error_Count"})

In [322]:
error_analysis

           Batch_Name      Error_Type  Error_Count
0          Crawley_11    Over Capture            2
1          Crawley_11   Under Capture            2
2          Crawley_11           Query            1
3          Crawley_11       Wrong Tag            1
4        Dartford_176           Query            6
5        Dartford_176    Over Capture            2
6        Dartford_176   Under Capture            1
7        Dartford_176  Wrong Location            1
8        Dartford_176       Wrong Tag            1
9          Exeter_145       Wrong Tag            4
10         Exeter_145    Over Capture            2
11         Exeter_145           Query            2
12         Exeter_145   Under Capture            2
13         Exeter_145  Wrong Location            1
14  Monmouthshire_145       Wrong Tag            3
15  Monmouthshire_145   Under Capture            1
16  Monmouthshire_145  Wrong Location            1
17           Powys_90           Query            4
18           Powys_90       Wrong Tag            3
19           Powys_90    Over Capture            2
20           Powys_90   Under Capture            2
21           Powys_90  Wrong Location            2
22    Test Valley_154       Wrong Tag            4
23    Test Valley_154   Under Capture            3
24    Test Valley_154           Query            2
25    Test Valley_154    Over Capture            1

In [323]:
# user level error analysis
# Which users are making which type of errors 

error_df.groupby("User_Clean")["Error_Type"].value_counts()

User_Clean      Error_Type
Alex Morgan     Wrong Tag         3
                Under Capture     2
                Wrong Location    1
Daniel Jones    Wrong Tag         3
                Query             1
Ethan Williams  Over Capture      2
                Query             2
                Wrong Location    1
                Wrong Tag         1
Jamie Smith     Wrong Tag         1
Maya Patel      Over Capture      1
Noah Davies     Under Capture     5
                Wrong Location    2
                Over Capture      1
                Query             1
                Wrong Tag         1
Olivia Brown    Query             8
                Under Capture     2
                Over Capture      1
                Wrong Tag         1
Priya Shah      Query             2
                Under Capture     2
                Wrong Tag         2
                Over Capture      1
Sam Taylor      Wrong Tag         2
                Over Capture      1
                Query             1
                Wrong Location    1
Sophie Evans    Over Capture      2
                Wrong Tag         2
Name: count, dtype: int64

In [324]:
# cleaning the table
user_error_analysis = error_df.groupby("User_Clean")["Error_Type"].value_counts().to_frame().reset_index()

In [325]:
# renaming the count columns as error count for user error analysis
user_error_analysis = user_error_analysis.rename(columns={"count": "Error_Count"})

In [326]:
user_error_analysis

        User_Clean      Error_Type  Error_Count
0      Alex Morgan       Wrong Tag            3
1      Alex Morgan   Under Capture            2
2      Alex Morgan  Wrong Location            1
3     Daniel Jones       Wrong Tag            3
4     Daniel Jones           Query            1
5   Ethan Williams    Over Capture            2
6   Ethan Williams           Query            2
7   Ethan Williams  Wrong Location            1
8   Ethan Williams       Wrong Tag            1
9      Jamie Smith       Wrong Tag            1
10      Maya Patel    Over Capture            1
11     Noah Davies   Under Capture            5
12     Noah Davies  Wrong Location            2
13     Noah Davies    Over Capture            1
14     Noah Davies           Query            1
15     Noah Davies       Wrong Tag            1
16    Olivia Brown           Query            8
17    Olivia Brown   Under Capture            2
18    Olivia Brown    Over Capture            1
19    Olivia Brown       Wrong Tag            1
20      Priya Shah           Query            2
21      Priya Shah   Under Capture            2
22      Priya Shah       Wrong Tag            2
23      Priya Shah    Over Capture            1
24      Sam Taylor       Wrong Tag            2
25      Sam Taylor    Over Capture            1
26      Sam Taylor           Query            1
27      Sam Taylor  Wrong Location            1
28    Sophie Evans    Over Capture            2
29    Sophie Evans       Wrong Tag            2

In [327]:
# How is each user performing overall?
# Calculating the total number of QC records for each user across all batches 
user_total_qc = df.groupby("User_Clean")["OA_Charge_ID"].count()

In [328]:
user_total_qc

User_Clean
Alex Morgan        86
Daniel Jones       96
Ethan Williams    108
Jamie Smith       106
Maya Patel        101
Noah Davies       101
Olivia Brown       92
Priya Shah         99
Sam Taylor        107
Sophie Evans      104
Name: OA_Charge_ID, dtype: int64

In [329]:
# total errors per user
user_errors = df[df["QC_Result"] == "Error"].groupby("User_Clean")["OA_Charge_ID"].count()

In [330]:
user_errors

User_Clean
Alex Morgan        6
Daniel Jones       4
Ethan Williams     6
Jamie Smith        1
Maya Patel         1
Noah Davies       10
Olivia Brown      12
Priya Shah         7
Sam Taylor         5
Sophie Evans       4
Name: OA_Charge_ID, dtype: int64

In [331]:
user_correct = df[df["QC_Result"] == "Correct"].groupby("User_Clean")["OA_Charge_ID"].count()

In [332]:
user_correct

User_Clean
Alex Morgan        80
Daniel Jones       92
Ethan Williams    102
Jamie Smith       105
Maya Patel        100
Noah Davies        91
Olivia Brown       80
Priya Shah         92
Sam Taylor        102
Sophie Evans      100
Name: OA_Charge_ID, dtype: int64

In [333]:
metrics = pd.DataFrame({
    "Total_QC": user_total_qc,
    "Error": user_errors,
    "Correct": user_correct
})

In [334]:
metrics

                Total_QC  Error  Correct
User_Clean
Alex Morgan           86      6       80
Daniel Jones          96      4       92
Ethan Williams       108      6      102
Jamie Smith          106      1      105
Maya Patel           101      1      100
Noah Davies          101     10       91
Olivia Brown          92     12       80
Priya Shah            99      7       92
Sam Taylor           107      5      102
Sophie Evans         104      4      100

In [335]:
metrics["Error_Rate"] = metrics["Error"]/metrics["Total_QC"] * 100

In [336]:
metrics

                Total_QC  Error  Correct  Error_Rate
User_Clean
Alex Morgan           86      6       80    6.976744
Daniel Jones          96      4       92    4.166667
Ethan Williams       108      6      102    5.555556
Jamie Smith          106      1      105    0.943396
Maya Patel           101      1      100    0.990099
Noah Davies          101     10       91    9.900990
Olivia Brown          92     12       80   13.043478
Priya Shah            99      7       92    7.070707
Sam Taylor           107      5      102    4.672897
Sophie Evans         104      4      100    3.846154

In [337]:
metrics["Quality"] = metrics["Correct"]/metrics["Total_QC"] * 100

In [338]:
metrics

                Total_QC  Error  Correct  Error_Rate    Quality
User_Clean
Alex Morgan           86      6       80    6.976744  93.023256
Daniel Jones          96      4       92    4.166667  95.833333
Ethan Williams       108      6      102    5.555556  94.444444
Jamie Smith          106      1      105    0.943396  99.056604
Maya Patel           101      1      100    0.990099  99.009901
Noah Davies          101     10       91    9.900990  90.099010
Olivia Brown          92     12       80   13.043478  86.956522
Priya Shah            99      7       92    7.070707  92.929293
Sam Taylor           107      5      102    4.672897  95.327103
Sophie Evans         104      4      100    3.846154  96.153846

In [339]:
# weekly performance to see if each  user is improving, staying consistent, or getting worse over time
weekly_total_qc = df.groupby(["User_Clean", "Week"])["OA_Charge_ID"].count()

In [340]:
weekly_total_qc

User_Clean      Week
Alex Morgan     1       50
                2       36
Daniel Jones    1       53
                2       43
Ethan Williams  1       60
                2       48
Jamie Smith     1       48
                2       58
Maya Patel      1       67
                2       34
Noah Davies     1       56
                2       45
Olivia Brown    1       56
                2       36
Priya Shah      1       54
                2       45
Sam Taylor      1       62
                2       45
Sophie Evans    1       56
                2       48
Name: OA_Charge_ID, dtype: int64

In [341]:
# weekly errors (how many errors did each user make in each week)?
weekly_error = df[df["QC_Result"] == "Error"].groupby(["User_Clean", "Week"])["OA_Charge_ID"].count()

In [342]:
weekly_error

User_Clean      Week
Alex Morgan     1       2
                2       4
Daniel Jones    1       1
                2       3
Ethan Williams  1       2
                2       4
Jamie Smith     1       1
Maya Patel      2       1
Noah Davies     1       5
                2       5
Olivia Brown    1       8
                2       4
Priya Shah      1       3
                2       4
Sam Taylor      1       1
                2       4
Sophie Evans    1       3
                2       1
Name: OA_Charge_ID, dtype: int64

In [343]:
# weekly correct (how many QC records were correct for each user in each week)
weekly_correct = df[df["QC_Result"] == "Correct"].groupby(["User_Clean", "Week"])["OA_Charge_ID"].count()

In [344]:
weekly_correct

User_Clean      Week
Alex Morgan     1       48
                2       32
Daniel Jones    1       52
                2       40
Ethan Williams  1       58
                2       44
Jamie Smith     1       47
                2       58
Maya Patel      1       67
                2       33
Noah Davies     1       51
                2       40
Olivia Brown    1       48
                2       32
Priya Shah      1       51
                2       41
Sam Taylor      1       61
                2       41
Sophie Evans    1       53
                2       47
Name: OA_Charge_ID, dtype: int64

In [345]:
weekly_metrics = pd.DataFrame({
    "Total_QC": weekly_total_qc,
    "Correct": weekly_correct,
    "Errors": weekly_error
})

In [346]:
weekly_metrics

                     Total_QC  Correct  Errors
User_Clean     Week
Alex Morgan    1           50       48     2.0
               2           36       32     4.0
Daniel Jones   1           53       52     1.0
               2           43       40     3.0
Ethan Williams 1           60       58     2.0
               2           48       44     4.0
Jamie Smith    1           48       47     1.0
               2           58       58     NaN
Maya Patel     1           67       67     NaN
               2           34       33     1.0
Noah Davies    1           56       51     5.0
               2           45       40     5.0
Olivia Brown   1           56       48     8.0
               2           36       32     4.0
Priya Shah     1           54       51     3.0
               2           45       41     4.0
Sam Taylor     1           62       61     1.0
               2           45       41     4.0
Sophie Evans   1           56       53     3.0
               2           48       47     1.0

In [347]:
# weekly error rate
# what percentage of each user's QC records were errors in each week 
weekly_metrics["Error_Rate"] = weekly_metrics["Errors"]/weekly_metrics["Total_QC"] * 100

In [348]:
weekly_metrics

                     Total_QC  Correct  Errors  Error_Rate
User_Clean     Week
Alex Morgan    1           50       48     2.0    4.000000
               2           36       32     4.0   11.111111
Daniel Jones   1           53       52     1.0    1.886792
               2           43       40     3.0    6.976744
Ethan Williams 1           60       58     2.0    3.333333
               2           48       44     4.0    8.333333
Jamie Smith    1           48       47     1.0    2.083333
               2           58       58     NaN         NaN
Maya Patel     1           67       67     NaN         NaN
               2           34       33     1.0    2.941176
Noah Davies    1           56       51     5.0    8.928571
               2           45       40     5.0   11.111111
Olivia Brown   1           56       48     8.0   14.285714
               2           36       32     4.0   11.111111
Priya Shah     1           54       51     3.0    5.555556
               2           45       41     4.0    8.888889
Sam Taylor     1           62       61     1.0    1.612903
               2           45       41     4.0    8.888889
Sophie Evans   1           56       53     3.0    5.357143
               2           48       47     1.0    2.083333

In [349]:
# weekly quality rate
weekly_metrics["Quality_Rate"] = weekly_metrics["Correct"]/weekly_metrics["Total_QC"] * 100

In [350]:
weekly_metrics

                     Total_QC  Correct  Errors  Error_Rate  Quality_Rate
User_Clean     Week
Alex Morgan    1           50       48     2.0    4.000000     96.000000
               2           36       32     4.0   11.111111     88.888889
Daniel Jones   1           53       52     1.0    1.886792     98.113208
               2           43       40     3.0    6.976744     93.023256
Ethan Williams 1           60       58     2.0    3.333333     96.666667
               2           48       44     4.0    8.333333     91.666667
Jamie Smith    1           48       47     1.0    2.083333     97.916667
               2           58       58     NaN         NaN    100.000000
Maya Patel     1           67       67     NaN         NaN    100.000000
               2           34       33     1.0    2.941176     97.058824
Noah Davies    1           56       51     5.0    8.928571     91.071429
               2           45       40     5.0   11.111111     88.888889
Olivia Brown   1           56       48     8.0   14.285714     85.714286
               2           36       32     4.0   11.111111     88.888889
Priya Shah     1           54       51     3.0    5.555556     94.444444
               2           45       41     4.0    8.888889     91.111111
Sam Taylor     1           62       61     1.0    1.612903     98.387097
               2           45       41     4.0    8.888889     91.111111
Sophie Evans   1           56       53     3.0    5.357143     94.642857
               2           48       47     1.0    2.083333     97.916667

In [351]:
# inspecting one user 
weekly_metrics.loc["Alex Morgan"]

      Total_QC  Correct  Errors  Error_Rate  Quality_Rate
Week
1           50       48     2.0    4.000000     96.000000
2           36       32     4.0   11.111111     88.888889

In [352]:
# how is each user performing day by day 
daily_total_qc = df.groupby(["User_Clean", "Date"])["OA_Charge_ID"].count()

In [353]:
daily_total_qc

User_Clean    Date
Alex Morgan   2026-01-05    2
              2026-01-06    1
              2026-01-08    1
              2026-01-10    2
              2026-01-11    2
                           ..
Sophie Evans  2026-03-20    2
              2026-03-21    4
              2026-03-22    2
              2026-03-25    2
              2026-03-27    1
Name: OA_Charge_ID, Length: 530, dtype: int64

In [354]:
# daily performance metrics 
# daily errors
daily_errors = df[df["QC_Result"] == "Error"].groupby(["User_Clean", "Date"])["OA_Charge_ID"].count()
daily_errors

User_Clean      Date
Alex Morgan     2026-01-26    1
                2026-02-07    1
                2026-02-17    1
                2026-03-10    1
                2026-03-12    1
                2026-03-13    1
Daniel Jones    2026-01-21    1
                2026-01-30    1
                2026-03-09    1
                2026-03-10    1
Ethan Williams  2026-01-23    1
                2026-01-28    1
                2026-02-09    1
                2026-02-12    1
                2026-02-18    1
                2026-02-24    1
Jamie Smith     2026-01-24    1
Maya Patel      2026-03-09    1
Noah Davies     2026-01-06    1
                2026-01-25    1
                2026-01-26    1
                2026-02-03    1
                2026-02-10    1
                2026-02-11    1
                2026-02-21    1
                2026-02-27    1
                2026-03-07    1
                2026-03-27    1
Olivia Brown    2026-01-20    2
                2026-02-06    1
                2026-02-16    3
                2026-02-22    1
                2026-02-23    1
                2026-03-20    1
                2026-03-23    2
                2026-03-26    1
Priya Shah      2026-01-08    1
                2026-01-14    1
                2026-01-23    1
                2026-01-24    1
                2026-01-29    1
                2026-02-13    1
                2026-03-13    1
Sam Taylor      2026-01-12    1
                2026-02-09    1
                2026-02-13    1
                2026-03-11    1
                2026-03-16    1
Sophie Evans    2026-01-09    1
                2026-02-27    1
                2026-03-02    1
                2026-03-05    1
Name: OA_Charge_ID, dtype: int64

In [355]:
# daily correct charges
daily_correct = df[df["QC_Result"] == "Correct"].groupby(["User_Clean", "Date"])["OA_Charge_ID"].count()
daily_correct

User_Clean    Date
Alex Morgan   2026-01-05    2
              2026-01-06    1
              2026-01-08    1
              2026-01-10    2
              2026-01-11    2
                           ..
Sophie Evans  2026-03-20    2
              2026-03-21    4
              2026-03-22    2
              2026-03-25    2
              2026-03-27    1
Name: OA_Charge_ID, Length: 515, dtype: int64

In [356]:
daily_metrics = pd.DataFrame ({
    "Total_QC": daily_total_qc,
    "Correct": daily_correct,
    "Errors": daily_errors
})

daily_metrics

                         Total_QC  Correct  Errors
User_Clean   Date
Alex Morgan  2026-01-05         2      2.0     NaN
             2026-01-06         1      1.0     NaN
             2026-01-08         1      1.0     NaN
             2026-01-10         2      2.0     NaN
             2026-01-11         2      2.0     NaN
...                           ...      ...     ...
Sophie Evans 2026-03-20         2      2.0     NaN
             2026-03-21         4      4.0     NaN
             2026-03-22         2      2.0     NaN
             2026-03-25         2      2.0     NaN
             2026-03-27         1      1.0     NaN

[530 rows x 3 columns]

In [357]:
# replacing NaN with 0 since here it means that the user did not make any errors 
daily_metrics["Errors"] = daily_metrics["Errors"].fillna(0)
daily_metrics

                         Total_QC  Correct  Errors
User_Clean   Date
Alex Morgan  2026-01-05         2      2.0     0.0
             2026-01-06         1      1.0     0.0
             2026-01-08         1      1.0     0.0
             2026-01-10         2      2.0     0.0
             2026-01-11         2      2.0     0.0
...                           ...      ...     ...
Sophie Evans 2026-03-20         2      2.0     0.0
             2026-03-21         4      4.0     0.0
             2026-03-22         2      2.0     0.0
             2026-03-25         2      2.0     0.0
             2026-03-27         1      1.0     0.0

[530 rows x 3 columns]

In [358]:
# replacing NaN with 0 since here it means that the user did not make any errors 
daily_metrics["Errors"] = daily_metrics["Errors"].fillna(0)
daily_metrics

                         Total_QC  Correct  Errors
User_Clean   Date
Alex Morgan  2026-01-05         2      2.0     0.0
             2026-01-06         1      1.0     0.0
             2026-01-08         1      1.0     0.0
             2026-01-10         2      2.0     0.0
             2026-01-11         2      2.0     0.0
...                           ...      ...     ...
Sophie Evans 2026-03-20         2      2.0     0.0
             2026-03-21         4      4.0     0.0
             2026-03-22         2      2.0     0.0
             2026-03-25         2      2.0     0.0
             2026-03-27         1      1.0     0.0

[530 rows x 3 columns]

In [359]:
daily_metrics["Correct"] = daily_metrics["Correct"].fillna(0)
daily_metrics

                         Total_QC  Correct  Errors
User_Clean   Date
Alex Morgan  2026-01-05         2      2.0     0.0
             2026-01-06         1      1.0     0.0
             2026-01-08         1      1.0     0.0
             2026-01-10         2      2.0     0.0
             2026-01-11         2      2.0     0.0
...                           ...      ...     ...
Sophie Evans 2026-03-20         2      2.0     0.0
             2026-03-21         4      4.0     0.0
             2026-03-22         2      2.0     0.0
             2026-03-25         2      2.0     0.0
             2026-03-27         1      1.0     0.0

[530 rows x 3 columns]

In [360]:
daily_metrics.isnull().sum()

Total_QC    0
Correct     0
Errors      0
dtype: int64

In [361]:
# daily error rates
daily_metrics["Error_Rate"] = daily_metrics["Errors"]/daily_metrics["Total_QC"] * 100
daily_metrics

                         Total_QC  Correct  Errors  Error_Rate
User_Clean   Date
Alex Morgan  2026-01-05         2      2.0     0.0         0.0
             2026-01-06         1      1.0     0.0         0.0
             2026-01-08         1      1.0     0.0         0.0
             2026-01-10         2      2.0     0.0         0.0
             2026-01-11         2      2.0     0.0         0.0
...                           ...      ...     ...         ...
Sophie Evans 2026-03-20         2      2.0     0.0         0.0
             2026-03-21         4      4.0     0.0         0.0
             2026-03-22         2      2.0     0.0         0.0
             2026-03-25         2      2.0     0.0         0.0
             2026-03-27         1      1.0     0.0         0.0

[530 rows x 4 columns]

In [362]:
# daily quality
daily_metrics["Quality"] = daily_metrics["Correct"]/daily_metrics["Total_QC"]* 100
daily_metrics

                         Total_QC  Correct  Errors  Error_Rate  Quality
User_Clean   Date
Alex Morgan  2026-01-05         2      2.0     0.0         0.0    100.0
             2026-01-06         1      1.0     0.0         0.0    100.0
             2026-01-08         1      1.0     0.0         0.0    100.0
             2026-01-10         2      2.0     0.0         0.0    100.0
             2026-01-11         2      2.0     0.0         0.0    100.0
...                           ...      ...     ...         ...      ...
Sophie Evans 2026-03-20         2      2.0     0.0         0.0    100.0
             2026-03-21         4      4.0     0.0         0.0    100.0
             2026-03-22         2      2.0     0.0         0.0    100.0
             2026-03-25         2      2.0     0.0         0.0    100.0
             2026-03-27         1      1.0     0.0         0.0    100.0

[530 rows x 5 columns]

In [476]:
# error type analysis
# filtering out all the no error cases and only keeping the errors ones
error_df = df[df["Error_Type"] != "No Error"]

In [478]:
# count each error type for each user
user_error_counts = error_df.groupby(["User_Clean","Error_Type"])["OA_Charge_ID"].count()

In [480]:
user_error_counts

User_Clean      Error_Type
Alex Morgan     Under Capture     2
                Wrong Location    1
                Wrong Tag         3
Daniel Jones    Query             1
                Wrong Tag         3
Ethan Williams  Over Capture      2
                Query             2
                Wrong Location    1
                Wrong Tag         1
Jamie Smith     Wrong Tag         1
Maya Patel      Over Capture      1
Noah Davies     Over Capture      1
                Query             1
                Under Capture     5
                Wrong Location    2
                Wrong Tag         1
Olivia Brown    Over Capture      1
                Query             8
                Under Capture     2
                Wrong Tag         1
Priya Shah      Over Capture      1
                Query             2
                Under Capture     2
                Wrong Tag         2
Sam Taylor      Over Capture      1
                Query             1
                Wrong Location    1
                Wrong Tag         2
Sophie Evans    Over Capture      2
                Wrong Tag         2
Name: OA_Charge_ID, dtype: int64

In [482]:
user_error_analysis = user_error_counts.reset_index()

In [484]:
user_error_analysis.head()

     User_Clean      Error_Type  OA_Charge_ID
0   Alex Morgan   Under Capture             2
1   Alex Morgan  Wrong Location             1
2   Alex Morgan       Wrong Tag             3
3  Daniel Jones           Query             1
4  Daniel Jones       Wrong Tag             3

In [486]:
user_error_analysis = user_error_analysis.rename(
    columns = {"OA_Charge_ID": "Error_Count"}
)
user_error_analysis.head()

     User_Clean      Error_Type  Error_Count
0   Alex Morgan   Under Capture            2
1   Alex Morgan  Wrong Location            1
2   Alex Morgan       Wrong Tag            3
3  Daniel Jones           Query            1
4  Daniel Jones       Wrong Tag            3

In [504]:
# each user most common error
error_type_summary = error_df.groupby("Error_Type")["OA_Charge_ID"].count().reset_index()

In [506]:
error_type_summary

       Error_Type  OA_Charge_ID
0    Over Capture             9
1           Query            15
2   Under Capture            11
3  Wrong Location             5
4       Wrong Tag            16

In [510]:
error_type_summary = error_type_summary.rename(
    columns = {"OA_Charge_ID": "Error_Count"}
)
error_type_summary

       Error_Type  Error_Count
0    Over Capture            9
1           Query           15
2   Under Capture           11
3  Wrong Location            5
4       Wrong Tag           16

In [522]:
# identifying each user's most common error types
user_error_analysis_sorted = user_error_analysis.sort_values(
    by=["User_Clean", "Error_Count"], ascending=[True, False]
)

user_error_analysis.head(10)

       User_Clean      Error_Type  Error_Count
0     Alex Morgan   Under Capture            2
1     Alex Morgan  Wrong Location            1
2     Alex Morgan       Wrong Tag            3
3    Daniel Jones           Query            1
4    Daniel Jones       Wrong Tag            3
5  Ethan Williams    Over Capture            2
6  Ethan Williams           Query            2
7  Ethan Williams  Wrong Location            1
8  Ethan Williams       Wrong Tag            1
9     Jamie Smith       Wrong Tag            1

In [518]:
# keep only the top errors for each users
top_user_errors = user_error_analysis_sorted.drop_duplicates(
    subset=["User_Clean"],
    keep="first"
)
top_user_errors

        User_Clean     Error_Type  Error_Count
2      Alex Morgan      Wrong Tag            3
4     Daniel Jones      Wrong Tag            3
5   Ethan Williams   Over Capture            2
9      Jamie Smith      Wrong Tag            1
10      Maya Patel   Over Capture            1
13     Noah Davies  Under Capture            5
17    Olivia Brown          Query            8
21      Priya Shah          Query            2
27      Sam Taylor      Wrong Tag            2
28    Sophie Evans   Over Capture            2